### PR TITLE
Optimizer hints v1

### PR DESCRIPTION
**Pull request by RoderickJDunn**
Added support for inserting optimizer hints into Oracle and MySQL queries.

For example, with the following Oracle table
```
> c = Compiler(Oracle(host='host', database='db', thread_count=2, user='user'))
> t = table("point")
```

You can now create a select query with a PARALLEL optimization hint as follows
```
> q = c.compile(t.where(this.b > 10).select(this.b, optimizer_hints='PARALLEL(a 16)'))
> print(q)
SELECT /*+ PARALLEL(a 16) */ "b" FROM "point" WHERE ("b" > 10)
```

### CODE REVIEW

**Comment by erezsh** [comment]
Cool! But why not make the base raise `NotImplementedError`? That makes more sense to me than overriding every database that doesn't support it.

**Comment by RoderickJDunn** [comment]
I went back and forth but ended up with this because the `/*+ */` syntax is supported by 3 databases so figured I could reuse the same builder for all those. I see mssql isn't supported yet though so you're right, it makes more sense to raise the error from base.

Also fixing the unit test issues now

**Comment by erezsh** [comment]
Sounds good. If you want to re-use this method, you can either use mixin inheritance, or just create a module function and call it from each class.

**Comment by RoderickJDunn** [comment]
I implemented it using a mixin as you suggested, but its not 100% clear to me what the `MIXINS` property does in Dialects. Is it basically a list of mixins that are _supported_ by the dialect, but only if a user chooses to load them it explicitly?

**Comment by erezsh** [comment]
Yeah, sorry, I accidentally mislead you. I meant a mixin as a concept (https://en.wikipedia.org/wiki/Mixin), not the specific AbstractMixin mechanism, which is a bit of an overkill for this feature.

But it's not bad that you did it this way. Maybe it's even for the best!

Here is how users can use mixins: https://sqeleton.readthedocs.io/en/latest/intro.html#dialect-mixins

And in the future I plan to make that interface a little bit nicer too.

**Comment by RoderickJDunn** [comment]
TY, I'll leave this as is for now then.

**Comment by erezsh** [comment]
Merged. Sorry for the delay, I was on vacation.

Thank you for the contribution!

**Pull request merged**
