### PR TITLE
Support 3-part paths in DuckDB

### LINKED ISSUE #21: Error when connecting to DuckDB with `data-diff --dbt`
### Details

I was trying to run the following command when using a [custom fork](https://github.com/dbeatty10/data-diff/pull/1) that added support for duckdb connections:
```
data-diff --dbt
```

But I got the following error:
```
ERROR - DuckDB: Bad table path for <data_diff.databases.duckdb.DuckDB object at 0x10b67f5e0>: 'main.dev.simple_model'. Expected form: schema.table
```

Here's the full stack trace:
```
Traceback (most recent call last):
  File "/Users/dbeatty/projects/data-diff/env/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dbeatty/projects/data-diff/data_diff/__main__.py", line 267, in main
    dbt_diff(
  File "/Users/dbeatty/projects/data-diff/data_diff/dbt.py", line 76, in dbt_diff
    _local_diff(diff_vars)
  File "/Users/dbeatty/projects/data-diff/data_diff/dbt.py", line 124, in _local_diff
    table1_columns = list(table1.get_schema())
  File "/Users/dbeatty/projects/data-diff/data_diff/table_segment.py", line 85, in get_schema
    return self.database.query_table_schema(self.table_path)
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/sqeleton/databases/base.py", line 389, in query_table_schema
    rows = self.query(self.select_table_schema(path), list)
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/sqeleton/databases/base.py", line 380, in select_table_schema
    schema, name = self._normalize_table_path(path)
  File "/Users/dbeatty/projects/data-diff/env/lib/python3.9/site-packages/sqeleton/databases/base.py", line 488, in _normalize_table_path
    raise ValueError(f"{self.name}: Bad table path for {self}: '{'.'.join(path)}'. Expected form: schema.table")
ValueError: DuckDB: Bad table path for <data_diff.databases.duckdb.DuckDB object at 0x10b67f5e0>: 'main.dev.simple_model'. Expected form: schema.table
```

### PR DESCRIPTION
**Pull request by dbeatty10**
resolves #21

### History
https://github.com/datafold/sqeleton/pull/22 was an initial attempt at unblocking `data-diff --dbt` for DuckDB. This is a second attempt.

Happy to iterate on this PR to fix things for DuckDB the proper way 🤗  Just let me know anything that needs to be addressed.

### Enabling 3-part fully-qualified names (FQN)
This PR enables all of the following for DuckDB connections:
- 1-part paths
- 2-part paths
- 3-part paths

The latter is especially important for the following reasons:
1. DuckDB 0.7.0 adds support for [attaching multiple databases](https://duckdb.org/docs/sql/statements/attach#name-qualification) ✨ 
2. It appears that prior to DuckDB 0.7.0, supplying a database/catalog in a 3-part path is allowed and handled gracefully

### Implementation details
Both DuckDB and Redshift have lots of similarities with PostgreSQL. So for this implementation, I just copied-pasted two methods from redshift to duckdb:
1. `select_table_schema`
2. `_normalize_table_path`

### Caveats
- I only tested with with DuckDB 0.6.1 -- I didn't test this with 0.7.0.
- 3-part paths worked for me with [duckcli 0.2.1](https://github.com/dbcli/duckcli) + DuckDB 0.6.1, even when I supplied a random identifier for the database
- 3-part paths worked for me with dbt-duckdb 1.3.4 + DuckDB 0.6.1, even when I supplied a random identifier for the database
- I didn't thoroughly investigate why 3-part paths worked in all of these cases, but I suspect DuckDB 0.6.1 just ignores the database specifier if supplied.

### See it in action

Wanna see it in action? Follow the simple instructions [here](https://github.com/dbeatty10/data-diff-demo#readme).

### CODE REVIEW

**Comment by erezsh** [comment]
Please base your PR on this recently merged PR - https://github.com/datafold/sqeleton/pull/18

Use a similar implementation.  (using lower() is probably wrong for duckdb)

Also add DuckDB to the simple test that it introduces.

**Comment by dbeatty10** [comment]
@erezsh I took a look at https://github.com/datafold/sqeleton/pull/18 and tried to align with it, namely:
- Copying the implementations of `select_table_schema` and `_normalize_table_path` from Postgres rather than Redshift
- Added DuckDB to the simple test that it introduces

Happy to iterate further as-needed.

**Comment by dlawin** [comment]
```  
File "/home/runner/work/sqeleton/sqeleton/sqeleton/databases/base.py", line 503, in _query_cursor
    c.execute(sql_code)
duckdb.CatalogException: Catalog Error: Table with name duckdb does not exist!
Did you mean "duckdb_types"?
```

**Comment by dbeatty10** [comment]
Thanks for sharing that error message from the CI checks @dlawin.

Are there any instructions I can follow for running the CI checks locally?

**Comment by erezsh** [comment]
@dbeatty10 See https://github.com/datafold/data-diff/blob/master/CONTRIBUTING.md#development-setup

**Comment by dlawin** [comment]
1 and 2 part drop statements are working, but seems that 3 part is not:
`DROP TABLE "duckdb"."main"."tbl__pti4o"` - > `duckdb.CatalogException: Catalog Error: Table with name duckdb does not exist!`

**Comment by dlawin** [comment]
Hmm I think the issue here is that duckdb doesn't seem to support 3 part paths. Only \<schema\>.\<object\>

**Comment by erezsh** [comment]
It should. https://duckdb.org/docs/sql/statements/attach#name-qualification

Are you sure you're using the newest duckdb?

**Comment by dlawin** [comment]
seems to be added in 0.7.0

**Comment by dbeatty10** [comment]
I have not tested how 3-part paths for `DELETE` statements works for the latest DuckDB (0.7.0), but I did just bump `pyproject.toml` to 0.7.0.

Could you try re-running the workflow?


### More detail
> Hmm I think the issue here is that duckdb doesn't seem to support 3 part paths. Only `<schema>.<object>`

I just did some more testing with DuckDB 0.6 (which is **not** the newest version).

It does support 3-part paths for `SELECT` statements, but it does not support 3-part paths for `DELETE` statements.

image

**Comment by dbeatty10** [comment]
> Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Looks like I need to generate a new lock file after updating `pyproject.toml`.

**Comment by dlawin** [comment]
> > Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
> 
> Looks like I need to generate a new lock file after updating `pyproject.toml`.

Oh I beat you to it. Works for me locally and the tests are passing here

**Review by dlawin — APPROVED** [review]

**Review by erezsh — APPROVED** [review]

**Pull request merged**
