### PR TITLE
Databricks: support 3 part id

### PR DESCRIPTION
**Pull request by dlawin**
Databricks supports a 3-part identifier in queries (catalog.schema.table)

### CODE REVIEW

**Comment by dlawin** [comment]
Wasn't sure of the best way to test this since databricks tests are limited at the moment. But you can see the `query_table_schema` returning info for each style

Screen Shot 2023-02-01 at 6 01 55 PM
Screen Shot 2023-02-01 at 5 59 20 PM
Screen Shot 2023-02-01 at 5 58 50 PM

**Comment by erezsh** [comment]
Looks good.

But the test in the screenshot isn't included in the PR.

**Comment by erezsh** [comment]
I think a better test would be to create and the drop a table, 3 times, once for each possible length, and make sure there is no error.

**Comment by dlawin** [comment]
> I think a better test would be to create and the drop a table, 3 times, once for each possible length, and make sure there is no error.

Manually? We don't include Databricks at all in automated tests currently

**Comment by erezsh** [comment]
That's fine. LGTM

**Pull request merged**
